name: Estimate 
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
    inputs:
      GIT_PROVIDER: 
        description: 'github/gitlab/bitbucket'
        required: true
      OPTIONS:
        description: 'file extension to look for in repository'
        required: true
      WEBHOOK_URL:
        description: 'webhook emit progress/error/done'
        required: false
      WEBHOOK_JWT:
        description: 'webhook jwt'
        required: false

env:
  REGISTRY_GH: ghcr.io
jobs:
  call-webhook-start:
    runs-on: ubuntu-latest
    steps:
    - name: Call Webhook with JWT
      run: |
        curl -X POST ${{ github.event.inputs.WEBHOOK_URL }}/${{ github.run_id }} \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ github.event.inputs.WEBHOOK_JWT }}" \
          -d '{"type": "start"}'
  estimate:
    runs-on: ubuntu-latest
    needs: call-webhook-start
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GH }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_READ_PACKAGES }}
      - name: Build and run with private image
        run: |
          docker pull ghcr.io/softwarity/xliff-ai-translator:${{ github.event.inputs.GIT_PROVIDER }}-estimator
          docker run  -e WEBHOOK_URL=${{ github.event.inputs.WEBHOOK_URL }}/${{ github.run_id }} \
                      -e WEBHOOK_JWT=${{ github.event.inputs.WEBHOOK_JWT }} \
                      -e OPTIONS=${{ github.event.inputs.OPTIONS }} \
                      --rm ghcr.io/softwarity/xliff-ai-translator:${{ github.event.inputs.GIT_PROVIDER }}-estimator
  call-webhook-done:
    runs-on: ubuntu-latest
    needs: estimate
    steps:
    - name: Call Webhook with JWT
      run: |
        curl -X POST ${{ github.event.inputs.WEBHOOK_URL }}/${{ github.run_id }} \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ github.event.inputs.WEBHOOK_JWT }}" \
          -d '{"type": "done"}'

