name: Build 
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
env:
  REGISTRY_GH: ghcr.io
  TOKEN: ${{ secrets.SOFTWARITY_ARCHWAY_TOKEN }}
  AI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
  REPOSITORY: softwarity/archway
  BRANCH: oss
  EXT_XLIFF: .fr.xlf
  STATE: nouveaux
  DRY_RUN: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GH }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and run with private image
        run: |
          "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY_GH }} -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/softwarity/xliff-ai-translator:github
          docker run -it -e REPOSITORY=${{ env.REPOSITORY }} -e BRANCH=${{ env.BRANCH }} -e STATE=${{ env.STATE }} -e EXT_XLIFF=${{ env.EXT_XLIFF}} -e AI_TOKEN=${{ env.AI_TOKEN }} -e TOKEN=${{ env.TOKEN }} --rm ghcr.io/softwarity/xliff-ai-translator:github


