name: Build 
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
env:
  REGISTRY_GH: ghcr.io
  TOKEN: ${{ secrets.SOFTWARITY_ARCHWAY_TOKEN }}
  AI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
  REPOSITORY: softwarity/archway
  GIT_PROVIDER: github
  BRANCH: oss
  EXT_XLIFF: .fr.xlf
  STATE: nouveaux
  PROCEEDED_STATE:  translated
  DRY_RUN: false
  CREDITS: 0
  WEBHOOK_URL: ''
  WEBHOOK_JWT: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GH }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_READ_PACKAGES }}
      - name: Build and run with private image
        run: |
          docker pull ghcr.io/softwarity/xliff-ai-translator:${{ env.GIT_PROVIDER }}
          docker run -e WEBHOOK_URL=${{ WEBHOOK_URL }} -e WEBHOOK_JWT=${{ WEBHOOK_JWT }} -e CREDITS=${{ en.CREDITS }} -e REPOSITORY=${{ env.REPOSITORY }} -e BRANCH=${{ env.BRANCH }} -e STATE=${{ env.STATE }} -e PROCEEDED_STATE=${{ env.PROCEEDED_STATE }} -e EXT_XLIFF=${{ env.EXT_XLIFF}} -e AI_TOKEN=${{ env.AI_TOKEN }} -e TOKEN=${{ env.TOKEN }} --rm ghcr.io/softwarity/xliff-ai-translator:${{ env.GIT_PROVIDER }}


